const OPTIONS = [
  '--help',
  '-h',
  '--history',
  '--include',
  '-i',
  '--head',
  '-I',
  '--verbose',
  '-v',
  '--quiet',
  '--follow',
  '-L',
  '--fail',
  '-f',
  '--method',
  '-X',
  '--headers',
  '-H',
  '--data',
  '-d',
  '--data-raw',
  '--query',
  '-q',
  '--output',
  '-o',
  '--cookie',
  '-b',
  '--cookie-jar',
  '--requests',
  '-n',
  '--concurrency',
  '-c',
  '--timeout',
  '-t',
  '--max-redirects',
  '--user',
  '-u',
  '--retry',
  '--retry-delay',
  '--profile',
  '-p',
  '--completions',
  '--save',
  '--use',
  '--aliases',
  '--delete-alias',
  '--form',
  '-F',
  '--proxy',
  '-x',
  '--write-out',
  '-w',
  '--dry-run',
  '--json',
  '-j',
  '--export',
  '-e',
]

const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS']

export function getBashScript(): string {
  return `# Bash completion for curly
# Generated by curly --completions bash
#
# Installation:
#   curly --completions install bash
#
# Or manually add to ~/.bashrc:
#   source <(curly --completions bash)
#   # OR
#   eval "$(curly --completions bash)"

_curly_completions() {
    local cur prev opts methods
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"

    # All available options
    opts="${OPTIONS.join(' ')}"

    # HTTP methods for -X/--method
    methods="${HTTP_METHODS.join(' ')}"

    # Handle option arguments
    case "\${prev}" in
        -X|--method)
            COMPREPLY=( $(compgen -W "\${methods}" -- "\${cur}") )
            return 0
            ;;
        -o|--output|-b|--cookie|--cookie-jar|-d|--data|-F|--form)
            # File completion
            COMPREPLY=( $(compgen -f -- "\${cur}") )
            return 0
            ;;
        --use|--delete-alias)
            # Try to complete alias names from config
            local aliases_file="\${HOME}/.config/curly/aliases.json"
            if [[ -f "\${aliases_file}" ]]; then
                local aliases=$(grep -o '"[^"]*":' "\${aliases_file}" | tr -d '":' | tr '\\n' ' ')
                COMPREPLY=( $(compgen -W "\${aliases}" -- "\${cur}") )
            fi
            return 0
            ;;
        -w|--write-out)
            # Write-out format variables
            local vars="http_code status_code time_total size_download"
            COMPREPLY=( $(compgen -W "\${vars}" -- "\${cur}") )
            return 0
            ;;
        -p|--profile)
            # Try to complete profile names from config
            local config_file="\${HOME}/.config/curly/config.json"
            if [[ -f "\${config_file}" ]]; then
                local profiles=$(grep -o '"[^"]*":' "\${config_file}" | grep -v '"default":' | grep -v '"profiles":' | tr -d '":' | tr '\\n' ' ')
                COMPREPLY=( $(compgen -W "\${profiles}" -- "\${cur}") )
            fi
            return 0
            ;;
        -H|--headers)
            # Common headers
            local headers="Content-Type: Authorization: Accept: X-API-Key: User-Agent:"
            COMPREPLY=( $(compgen -W "\${headers}" -- "\${cur}") )
            return 0
            ;;
        --completions)
            COMPREPLY=( $(compgen -W "bash zsh install" -- "\${cur}") )
            return 0
            ;;
        -n|--requests|-c|--concurrency|-t|--timeout|--retry|--retry-delay|--max-redirects)
            # Numeric values - no completion
            return 0
            ;;
        -e|--export)
            COMPREPLY=( $(compgen -W "json csv" -- "\${cur}") )
            return 0
            ;;
    esac

    # Complete options if current word starts with -
    if [[ "\${cur}" == -* ]]; then
        COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
        return 0
    fi

    # Default to URL/file completion
    COMPREPLY=( $(compgen -f -- "\${cur}") )
}

complete -F _curly_completions curly
`
}

export function getZshScript(): string {
  return `#compdef curly
# Zsh completion for curly
# Generated by curly --completions zsh
#
# Installation:
#   curly --completions install zsh
#
# Or manually add to ~/.zshrc:
#   source <(curly --completions zsh)
#   # OR
#   eval "$(curly --completions zsh)"

_curly() {
    local -a opts methods profiles

    # HTTP methods
    methods=(
        'GET:Retrieve a resource'
        'POST:Create a resource'
        'PUT:Update a resource'
        'PATCH:Partially update a resource'
        'DELETE:Delete a resource'
        'HEAD:Get headers only'
        'OPTIONS:Get allowed methods'
    )

    # Try to get profiles from config
    local config_file="\${HOME}/.config/curly/config.json"
    if [[ -f "\${config_file}" ]]; then
        profiles=(\${(f)"$(grep -o '"[^"]*":' "\${config_file}" | grep -v '"default":' | grep -v '"profiles":' | tr -d '":')"})
    fi

    _arguments -s \\
        '(-h --help)'{-h,--help}'[Show help message]' \\
        '--history[Show command history]' \\
        '(-X --method)'{-X,--method}'[HTTP method]:method:((\${methods}))' \\
        '*'{-H,--headers}'[Add header]:header:' \\
        '*'{-d,--data}'[Request data]:data:_files' \\
        '--data-raw[Raw request data]:data:' \\
        '*'{-q,--query}'[Query parameter]:query:' \\
        '(-o --output)'{-o,--output}'[Output file]:file:_files' \\
        '*'{-b,--cookie}'[Cookie]:cookie:_files' \\
        '--cookie-jar[Cookie jar file]:file:_files' \\
        '(-i --include)'{-i,--include}'[Include response headers]' \\
        '(-I --head)'{-I,--head}'[HEAD request only]' \\
        '(-v --verbose)'{-v,--verbose}'[Verbose output]' \\
        '--quiet[Suppress status line]' \\
        '(-n --requests)'{-n,--requests}'[Number of requests]:count:' \\
        '(-c --concurrency)'{-c,--concurrency}'[Concurrency level]:count:' \\
        '(-t --timeout)'{-t,--timeout}'[Timeout in ms]:milliseconds:' \\
        '(-L --follow)'{-L,--follow}'[Follow redirects]' \\
        '--max-redirects[Max redirects]:count:' \\
        '(-f --fail)'{-f,--fail}'[Fail on HTTP errors]' \\
        '(-u --user)'{-u,--user}'[Basic auth user:pass]:credentials:' \\
        '--retry[Retry count]:count:' \\
        '--retry-delay[Retry delay in ms]:milliseconds:' \\
        '(-p --profile)'{-p,--profile}'[Config profile]:profile:(\${profiles})' \\
        '--completions[Generate shell completions]:shell:(bash zsh install)' \\
        '--save[Save request as alias]:name:' \\
        '--use[Execute a saved alias]:alias:' \\
        '--aliases[List all saved aliases]' \\
        '--delete-alias[Delete a saved alias]:alias:' \\
        '*'{-F,--form}'[Multipart form data]:data:_files' \\
        '(-x --proxy)'{-x,--proxy}'[Proxy server URL]:url:' \\
        '(-w --write-out)'{-w,--write-out}'[Output format]:format:(http_code status_code time_total size_download)' \\
        '--dry-run[Show request details without sending]' \\
        '(-j --json)'{-j,--json}'[Output response as structured JSON]' \\
        '(-e --export)'{-e,--export}'[Export load test results]:format:(json csv)' \\
        '*:URL:_urls'
}

_curly "$@"
`
}
